// flow-typed signature: 9eedf8f3f1c5976243c86aed01d5456e
// flow-typed version: <<STUB>>/georedis_v3.1.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'georedis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'georedis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'georedis/lib/interfaceEmulated' {
  declare module.exports: any;
}

declare module 'georedis/lib/interfaceNative' {
  declare module.exports: any;
}

declare module 'georedis/lib/interfaceQueued' {
  declare module.exports: any;
}

declare module 'georedis/lib/query' {
  declare module.exports: any;
}

declare module 'georedis/lib/range' {
  declare module.exports: any;
}

declare module 'georedis/lib/util/helper' {
  declare module.exports: any;
}

declare module 'georedis/main' {
  declare module.exports: any;
}

declare module 'georedis/test/benchmark' {
  declare module.exports: any;
}

declare module 'georedis/test/testAutoDetect' {
  declare module.exports: any;
}

declare module 'georedis/test/testComponents' {
  declare module.exports: any;
}

declare module 'georedis/test/testEmulated' {
  declare module.exports: any;
}

declare module 'georedis/test/testFakeRedisEmulated' {
  declare module.exports: any;
}

declare module 'georedis/test/testIORedis' {
  declare module.exports: any;
}

declare module 'georedis/test/testIORedisNative' {
  declare module.exports: any;
}

declare module 'georedis/test/testNative' {
  declare module.exports: any;
}

// Filename aliases
declare module 'georedis/lib/interfaceEmulated.js' {
  declare module.exports: $Exports<'georedis/lib/interfaceEmulated'>;
}
declare module 'georedis/lib/interfaceNative.js' {
  declare module.exports: $Exports<'georedis/lib/interfaceNative'>;
}
declare module 'georedis/lib/interfaceQueued.js' {
  declare module.exports: $Exports<'georedis/lib/interfaceQueued'>;
}
declare module 'georedis/lib/query.js' {
  declare module.exports: $Exports<'georedis/lib/query'>;
}
declare module 'georedis/lib/range.js' {
  declare module.exports: $Exports<'georedis/lib/range'>;
}
declare module 'georedis/lib/util/helper.js' {
  declare module.exports: $Exports<'georedis/lib/util/helper'>;
}
declare module 'georedis/main.js' {
  declare module.exports: $Exports<'georedis/main'>;
}
declare module 'georedis/test/benchmark.js' {
  declare module.exports: $Exports<'georedis/test/benchmark'>;
}
declare module 'georedis/test/testAutoDetect.js' {
  declare module.exports: $Exports<'georedis/test/testAutoDetect'>;
}
declare module 'georedis/test/testComponents.js' {
  declare module.exports: $Exports<'georedis/test/testComponents'>;
}
declare module 'georedis/test/testEmulated.js' {
  declare module.exports: $Exports<'georedis/test/testEmulated'>;
}
declare module 'georedis/test/testFakeRedisEmulated.js' {
  declare module.exports: $Exports<'georedis/test/testFakeRedisEmulated'>;
}
declare module 'georedis/test/testIORedis.js' {
  declare module.exports: $Exports<'georedis/test/testIORedis'>;
}
declare module 'georedis/test/testIORedisNative.js' {
  declare module.exports: $Exports<'georedis/test/testIORedisNative'>;
}
declare module 'georedis/test/testNative.js' {
  declare module.exports: $Exports<'georedis/test/testNative'>;
}
